name: Verify build

on:
  push:
    branches:
      - '**'
      - '!develop'
      - '!master'
      - '!main'

jobs:
  deploy-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: '19'
      
      - name: Build
        env:
          REACT_APP_MUSIC_LAMBDA_URL: ${{ secrets.REACT_APP_MUSIC_LAMBDA_URL_TEST }}
          REACT_APP_TRACKLIST_JSON_URL: ${{ secrets.REACT_APP_TRACKLIST_JSON_URL_TEST }}
        run: |
          npm ci
          npm run build

